#![forbid(unsafe_code)]

use std::path::PathBuf;

#[derive(Clone, Debug)]
pub struct DesktopConfig {
    /// Hosted IndieBuild API. This is not the machine-local lifecycle control plane.
    pub api_base: String,
    /// Loopback-only giw-desktop-daemon endpoint.
    pub daemon_base: String,
    /// Local bearer token file generated by giw-desktop-daemon.
    pub daemon_token_file: PathBuf,
}

impl DesktopConfig {
    pub fn from_env() -> Self {
        let home = std::env::var_os("HOME")
            .or_else(|| std::env::var_os("USERPROFILE"))
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));

        return Self {
            api_base: std::env::var("GHA_INDIE_WORKER_API_BASE")
                .unwrap_or_else(|_| "https://indiebuild.dev".to_string()),
            daemon_base: std::env::var("GIW_DESKTOP_URL")
                .unwrap_or_else(|_| "http://127.0.0.1:18440".to_string()),
            daemon_token_file: std::env::var_os("GIW_DESKTOP_TOKEN_FILE")
                .map(PathBuf::from)
                .unwrap_or_else(|| home.join(".giw").join("desktop").join("token")),
        };
    }
}
